config/routes.rb
Rails.application.routes.draw do
  root 'lessons#index'
  
  devise_for :users
  resources :users
  
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  
  resources :lessons do 
    resources :charges
    resources :classrooms
    
  end
  resources :categories, only: [:show]
  
  resources :lessons do 
    resources :comments
  end

  namespace :admin do 
    root 'base#index'
    resources :users 
    resources :lessons
  end

  get 'static_pages/contact'
  get 'static_pages/about'
  get 'static_pages/faq'
  get 'static_pages/legal_notice'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :validatable
            
has_one_attached :avatar

has_many :followed_lessons, foreign_key: "student_id", class_name: "Classroom", dependent: :destroy
has_many :lessons, through: :followed_lessons
has_many :taught_lessons,  foreign_key: "teacher_id", class_name: "Lesson", dependent: :destroy

has_many :comments

validates :username, presence: true
validates :username, uniqueness: true

  def is_teacher? 
    if @current_user.taught_lessons.count > 0
    else
    end
  end
  
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_user!, :is_admin?
    
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end
    
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        if @user.destroy 
          flash[:warning] = "Le compte a bien été supprimé !"
          redirect_to root_path
        else
          render "new"
        end
    end   
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

def facebook

	@user = User.from_facebook(request.env['omniauth.auth'])
	if @user.persisted?
		sign_in_and_redirect @user, event: :authentification

	else
		session['devise.facebook'] = request.env['omniauth.auth']
		redirect_to new_user_registration_url
	end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @classrooms = Classroom.where(:student_id => @user.id)
    @taught_lessons = Lesson.where(:teacher_id => @user.id)
  end

  def destroy
    @user = current_user
    @user.destroy
    if @user.destroy 
      flash[:warning] = "Le compte a bien été supprimé !"
      redirect_to root_path
    else
      render "new"
    end
  end

  def new
    @user = User.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<body class="profile-page sidebar-collapse">
  <div class="page-header header-filter" data-parallax="true" style="background-image: url(/assets/background/back_show_user.jpg);"></div>
  <div class="main main-raised">
    <div class="profile-content">
      <div class="container">
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile">
              <div class="avatar">
                  <%if @user.avatar.attached?%>
                    <%= image_tag @user.avatar, alt: 'avatar', class:"img-raised rounded-circle img-fluid" %>
                  <%else%>
                    <%= image_tag "avatar/void_avatar.jpg", alt: 'avatar', class:"img-raised rounded-circle img-fluid" %>
                  <%end%>
              </div>
              <div class="name">
                <h3 class="title"><%= @user.username %></h3>
                <h6>Inscrit.e depuis le <%= @user.created_at.strftime("%m-%Y")%> </h6> 
                <% if current_user.admin? %>
                <a href="<%= admin_root_path %>" class="btn btn-rose btn-round">
                  <i class="material-icons">subject</i> Administrator
                </a>   
                <% else %>
                <%end %>
              </div>
            </div>
          </div>
        </div>
        <div class="description text-center">
          <p> <%= @user.description %> </p><br/><br/>
          <a href="/lessons/new">
          <button class="btn btn-success btn-lg btn-round">Proposer un cours<div class="ripple-container"></div></button>
          </a>
        </div>
        <div class="row">
          <div class="col-md-6 ml-auto mr-auto">
            <div class="profile-tabs">
              <ul class="nav nav-pills nav-pills-icons justify-content-center" role="tablist">
                <li class="nav-item">
                  <a class="nav-link" href="#subscribed" role="tab" data-toggle="tab">
                    <i class="material-icons">beenhere</i>
                    Mes abonnements
                  </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#mycourses" role="tab" data-toggle="tab">
                    <i class="material-icons">create</i>
                    Mes cours
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="tab-content tab-space">
          <div class="tab-pane text-center gallery" id="subscribed">
            <div class="row">
              <div class="col ml-auto">
              <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th class="text-center">#</th>
                        <th>Cours suivis</th>
                        <th>Catégorie</th>
                        <th>Professeur</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <% @classrooms.each do |classroom|%>
                    <tbody>
                        <td class="text-center"><%= classroom.id %></td>
                        <td><%= classroom.lesson.title %></td>
                        <td> <%= classroom.lesson.category %> </td>
                        <td><%= classroom.lesson.teacher.email %>   </td>
                        <td class="td-actions text-right">
                          <a  href="<%= lesson_path(classroom.lesson.id)%>" rel="tooltip" class="btn btn-success btn-just-icon btn-sm" data-original-title="" title="">
                            <i class="material-icons">done_outline</i>
                          </a>
                          <a  <%= link_to "exit_to_app" , lesson_classroom_path(lesson_url , classroom.id) , data: { toggle: "tooltip", placement: "right", title: "Se désabonner", confirm: "Es-tu sûr-e de vouloir quitter ce cours ?"} , method: :delete, class:"material-icons btn btn-warning btn-sm" %>
                          </a>
                        </td>
                    </tbody>
                    <% end %>
                  </table>
                </div>        
              </div>
            </div>
          </div>
          <div class="tab-pane text-center gallery" id="mycourses">
            <div class="row">
              <div class="col ml-auto">
              <div class="table-responsive">
                  <table class="table">
                    <thead>
                      <tr>
                        <th class="text-center">#</th>
                        <th>Titre du cours</th>
                        <th>Catégorie</th>
                        <th>Nombre élève</th>
                        <th>Actions</th>
                      </tr>
                    </thead>
                    <% @taught_lessons.each do |taught_lesson| %>
                    <tbody>
                        <td class="text-center"><%= taught_lesson.id %></td>
                        <td><%= taught_lesson.title %></td>
                        <td> <%= taught_lesson.category %> </td>
                        <td><%=Classroom.where(lesson_id: taught_lesson).count %>   </td>
                        <td class="td-actions text-right">
                          <a  href="<%= lesson_path(taught_lesson.id)%>" rel="tooltip" class="btn btn-success btn-just-icon btn-sm" data-original-title="" title="">
                            <i class="material-icons">done_outline</i>
                          </a>
                          <a  <%= link_to "edit", edit_lesson_path(taught_lesson.id), data: { toggle: "tooltip", placement: "right", title: "Éditer le cours"}, class:"material-icons btn btn-info btn-sm" %>
                          </a>
                          <a  <%= link_to "close", lesson_path(taught_lesson.id), data: { toggle: "tooltip", placement: "right", title: "Supprimer le cours", confirm: "Es-tu sûr.e de vouloir supprimer ce cours ?"} , method: :delete, class:"material-icons btn btn-warning btn-sm" %>
                          </a>
                        </td>
                    </tbody>
                    <% end %>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>