config/routes.rb
Rails.application.routes.draw do
  root 'lessons#index'
  
  devise_for :users
  resources :users
  
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  
  resources :lessons do 
    resources :charges
    resources :classrooms
    
  end
  resources :categories, only: [:show]
  
  resources :lessons do 
    resources :comments
  end

  namespace :admin do 
    root 'base#index'
    resources :users 
    resources :lessons
  end

  get 'static_pages/contact'
  get 'static_pages/about'
  get 'static_pages/faq'
  get 'static_pages/legal_notice'
end

app/models/lesson.rb
class Lesson < ApplicationRecord

    has_many   :classrooms, dependent: :destroy
    has_many   :students, class_name: "User", through: :classrooms
    
    belongs_to :teacher, class_name: "User"

    has_many :comments

    validates :title, presence: {message: "Le titre est nécessaire à la création d'un cours"}
    validates :title, uniqueness: {message: "Ce titre est déja pris, soyez unique"}
    validates :title , length: { in: 6..50 ,message: "Le titre doit contenir entre 6 et 50 caractères"}
    validates :content, presence: {message: "Un contenu est nécessaire à la création d'un cours"}
    validates :content, length: {minimum: 50 ,message: "Le contenu doit contenir au minimum 50 caractères"}
    validates :category, presence: true
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < ApplicationController
    before_action :authenticate_user!, :is_admin?

    def index
        @users = User.all
        @lessons = Lesson.all
    end

    def update 
        @lesson = Lesson.find(params[:id])
        if @lesson.update(checked: true)
            flash[:success] = "Le cours a bien été validé !"
            redirect_to admin_lessons_path
        else 
            flash[:warning] = "Le cours n'a pas été validé !"
            redirect_to admin_lessons_path
        end
    end
end
    


    

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :show]
  before_action :is_accessible?, only: [:show]

  def index
    @lessons = Lesson.where(checked: true)
    @users = User.all
  end

  def show
    @comment = Comment.new
    @comments = Comment.all
    @lesson = Lesson.find(params[:id])
    @students = [Lesson.find(params[:id]).students]
  end
  
  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(
      title: params[:lesson][:title], 
      content: params[:lesson][:content],
      category: params[:lesson][:category],
      price: params[:lesson][:price],
      summary: params[:lesson][:summary],
      teacher: current_user,
      checked: false)
    if @lesson.save 
      flash[:info] = "Votre cours est en cours de validation !"
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    Lesson.destroy(@lesson.id)
    if @lesson.destroy 
      flash[:warning] = "Votre cours a bien été supprimé !"
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(
      title: params[:lesson][:title], 
      content: params[:lesson][:content],
      category: params[:lesson][:category],
      price: params[:lesson][:price],
      summary: params[:lesson][:summary],
      checked: false)
      redirect_to @lesson
    else
      render :edit
    end
  end

  private

  def is_accessible?
    @lesson = Lesson.find(params[:id])
    paid_lesson = @lesson.classrooms.map {|c| c.student}.include?(current_user)
    if @lesson.price == 0 || @lesson.price == nil || paid_lesson
    elsif @lesson.teacher.id == current_user.id
    elsif current_user.admin == true
    else
      redirect_to  new_lesson_charge_path(@lesson.id)
    end
  end
end

app/helpers/lesson_helper.rb
module LessonHelper
  def is_student_to_current_lesson(lesson)
    lesson.students.include?(current_user)
  end
end

app/views/lessons/edit.html.erb
<body class="product-page sidebar-collapse">
  <div class="page-header header-filter" data-parallax="true" filter-color="rose" style="background-image: url(/assets/background/back_new_lesson.jpg);">
  </div>

  <div class="section">
    <div class="container">
        <div class="main main-raised main-product">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <h2 class="title">J'édite mon cours</h2>
                    <h5 class="description">Vous pouvez ici modifier votre propre cours. Chaque modification est soumise à l'approbation de l'équipe de Couture Academy.</h5>
                    <br/>
                <div class="media media-post">
                  <div class="media-body">
                    <%= form_with model: @lesson, local: true, class: "form" do |form| %>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group bmd-form-group">
                          <%= form.text_field :title, class: "form-control", placeholder: "Titre du cours" %>
                          <p> <%= @lesson.errors[:title].first %> </p>
                          <p> <%= @lesson.errors[:title].second %> </p>
                          <p> <%= @lesson.errors[:title].third %> </p>
                        </div>
                      </div>
                      <div class="col-md-6">
                      <p>Choisissez une catégorie</p>
                        <div class="form-group bmd-form-group">
                          <%= form.select :category,['Choisissez une catégorie', 'Les bases', 'Couture', 'Broderie', 'Modélisme'], disabled: 'Choisissez une catégorie' %>
                        </div>
                      </div>
                    </div>
                      <span class="bmd-form-group">
                      <%= form.text_area :summary, class: "form-control", placeholder: "Résumé du cours : Allez à l'essentiel et donnez envie aux futurs élèves de s'abonner - 250 caractères maximum" %>
                      </span><br/>
                      <span class="bmd-form-group">
                      <h6>Contenu du cours</h6>
                      <%= form.trix_editor :content, autofocus: true%>
                      <p> <%= @lesson.errors[:content].first %> </p>
                      <p> <%= @lesson.errors[:content].second %> </p>
                      </span><br/>
                    <div class="row">
                      <div class="col-md-8">
                        <div class="form-group bmd-form-group">
                          <div class="input-group">
                            <%= form.number_field :price, step: :any, class: "form-control", placeholder: "Prix (0 pour rendre le cours gratuit)"  %>
                            <div class="input-group-prepend">
                              <span class="input-group-text">
                                <i class="material-icons">euro</i>
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                      </div><br/>
                      <div class="media-footer" align="center">
                        <%= form.submit class: "btn btn-success btn-round", value: "Poster le cours" %>
                      </div>
                    <% end %>
                  </div>
                </div>
                </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/lessons/index.html.erb
  <div class="page-header header-filter" data-parallax="true" style="background-image: url(/assets/background/back_index_lesson.jpg);">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto">
          <div class="brand">
            <h1 class="title text-center">Apprenez à faire vos vêtements vous-même</h1><br/>
            <h4>Couture Academy est une plateforme de partage des connaissances et des savoir-faire liés à la couture. Que vous soyez passionné·e par la couture, la broderie, le modélisme ou même le tricot, vous pourrez aussi bien approfondir vos connaissances que partager votre expérience avec d’autres amateur·ice·s de Do It Yourself.
            </h4>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
        <div class="title">
          <br/><h3 class="title">Les catégories</h3>
            </div>
              <div class="row">
              <div class="col-md-3">
                <div class="card card-background" style="background-image: url(/assets/card/card_base.jpg);">
                  <div class="card-body">
                    <h3 class="card-title">Les bases</h3><br/><br/><br/><br/>
                    <a href="/categories/Les%20bases" class="btn btn-danger btn-round">
                      <i class="material-icons">subject</i> Voir les cours
                    </a>
                  </div>
                </div>
              </div>
              <div class="col-md-3">
                <div class="card card-background" style="background-image: url(/assets/card/card_embroidery.jpg);">
                  <div class="card-body">
                    <h3 class="card-title">Broderie</h3><br/><br/><br/><br/>
                    <a href="/categories/Broderie" class="btn btn-danger btn-round">
                      <i class="material-icons">subject</i> Voir les cours
                    </a>
                  </div>
                </div>
              </div>
              <div class="col-md-3">
                <div class="card card-background" style="background-image: url(/assets/card/card_sew.jpg);">
                  <div class="card-body">
                    <h3 class="card-title">Couture</h3><br/><br/><br/><br/>
                    <a href="/categories/Couture" class="btn btn-danger btn-round">
                      <i class="material-icons">subject</i> Voir les cours
                    </a>
                  </div>
                </div>
              </div>
              <div class="col-md-3">
                <div class="card card-background" style="background-image: url(/assets/card/card_model.jpg);">
                  <div class="card-body">
                    <h3 class="card-title">Modélisme</h3><br/><br/><br/><br/>
                    <a href="/categories/Modélisme" class="btn btn-danger btn-round">
                      <i class="material-icons">subject</i> Voir les cours
                    </a>
                  </div>
                </div>
              </div>
            </div>
      <div class="container" id="courses">
        <div class="title">
          <br/><h3 class="title">Tous nos cours</h3>
      </div>
      <div class="row">
      <% @lessons.each do |lesson|%>
              <div class="col-md-6 col-lg-4">
                <div class="rotating-card-container manual-flip" style="margin-bottom: 30px;">
                  <div class="card card-rotate" >
                    <div class="front front-background" style="background-image: url(/assets/card/card_lesson.jpg); height: 400px;">
                      <div class="card-body">
                        <h5 class="card-category card-category-social text-success">
                          <%= lesson.category %>
                        </h5>
                        <h4 class="card-title">
                          <%= lesson.title%>
                        </h4>
                        <p class="card-description">
                          <div><%= lesson.summary %></div>
                        </p>
                        <div class="card-footer ">
                        </div>
                        <div class="stats text-center">
                          <button type="button" name="button" class="btn btn-success btn-fill btn-round btn-rotate">
                            <i class="material-icons">refresh</i> En savoir plus
                          </button>
                        </div>
                      </div>
                    </div>
                    <div class="back" style="width: 289.984px;">
                      <div class="card-body">
                        <br>
                        <h5 class="card-title">
                          Lancez vous !
                        </h5>
                        <p class="card-description">
                          <%= lesson.summary %></p><br/>
                        <div class="author">
                          <h6>Proposé par <%= lesson.teacher.username %></h6>
                          <% if lesson.price == 0 || lesson.price == nil %>
                          <h6> Gratuit </h6>
                          <%else%>
                          <h6>Prix <%= lesson.price %></h6>
                          <%end%>
                        </div><br/>
                        <div class="stats text-center">
                          <a href="<%= lesson_path(lesson.id)%>" class="btn btn-rose btn-round">
                            <i class="material-icons">subject</i> Consulter
                          </a>
                        </div>
                        <br>
                        <button type="button" name="button" class="btn btn-link btn-round btn-rotate">
                          <i class="material-icons">refresh</i> Retour
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
      <% end %>
      </div>
    </div>
    </div>
  </div>

app/views/lessons/new.html.erb
<body class="product-page sidebar-collapse">
  <div class="page-header header-filter" data-parallax="true" filter-color="rose" style="background-image: url(/assets/background/back_new_lesson.jpg);"></div>
  <div class="section">
    <div class="container">
        <div class="main main-raised main-product">
            <div class="row">
                <div class="col-md-8 ml-auto mr-auto">
                    <h2 class="title">Je propose mon cours</h2>
                    <h5 class="description">Vous pouvez ici proposer votre propre cours. Chaque cours est soumis à l'approbation de l'équipe de Couture Academy. N'oubliez pas la mise en forme, un pavé de texte sans chapitres ni titre sera systématiquement refusé par notre équipe.</h5>
                    <h6 class="description">S'il est accepté, votre cours sera en ligne environ 24h après sa publication.</h6>
                    <br/>
                    <div class="media media-post">
                      <div class="media-body">
                        <%= form_with model: @lesson, local: true, class: "form" do |form| %>
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group bmd-form-group">
                              <%= form.text_field :title, class: "form-control", placeholder: "Titre du cours" %>
                              <p> <%= @lesson.errors[:title].first %> </p>
                              <p> <%= @lesson.errors[:title].second %> </p>
                              <p> <%= @lesson.errors[:title].third %> </p>
                            </div>
                          </div>
                          <div class="col-md-6">
                          <p>Choisissez une catégorie</p>
                            <div class="form-group bmd-form-group">
                              <%= form.select :category,['Choisissez une catégorie', 'Les bases', 'Couture', 'Broderie', 'Modélisme'], disabled: 'Choisissez une catégorie' %>
                            </div>
                          </div>
                        </div>
                          <span class="bmd-form-group">
                          <%= form.text_area :summary, class: "form-control", placeholder: "Résumé du cours : Allez à l'essentiel et donnez envie aux futurs élèves de s'abonner - 250 caractères maximum" %>
                          </span><br/>
                          <span class="bmd-form-group">
                          <h6>Contenu du cours</h6>
                          <%= form.trix_editor :content, autofocus: true%>
                          <p> <%= @lesson.errors[:content].first %> </p>
                          <p> <%= @lesson.errors[:content].second %> </p>
                          </span><br/>
                        <div class="row">
                          <div class="col-md-8">
                            <div class="form-group bmd-form-group">
                              <div class="input-group">
                                <%= form.number_field :price, step: :any, class: "form-control", placeholder: "Prix (0 pour rendre le cours gratuit)" %>
                                <div class="input-group-prepend">
                                  <span class="input-group-text">
                                    <i class="material-icons">euro</i>
                                  </span>
                                </div>
                              </div>
                            </div>
                          </div>
                          </div><br/>
                          <div class="media-footer" align="center">
                            <%= form.submit class: "btn btn-success btn-round", value: "Poster le cours" %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/lessons/show.html.erb
<body class="blog-post sidebar-collapse">
  <div class="page-header header-filter" data-parallax="true" style="background-image: url(/assets/background/back_show_lesson.jpg);">
    <div class="container">
      <div class="row">
        <div class="col-md-8 ml-auto mr-auto text-center">
          <h1 class="title"><%= @lesson.title %></h1>
          <h4>Un cours proposé par <%= @lesson.teacher.username %></h4>
          <br>
        </div>
      </div>
    </div>
  </div>
  <div class="main main-raised">
    <div class="container">
      <div class="section section-text">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <% if is_student_to_current_lesson(@lesson)  %>
              <a class="btn btn-primary btn-round" data-toggle="tab"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Inscrit.e</font></font></a>
              <div class="ripple-container"></div>
              <% else %>
                <%= link_to "S'inscrire", lesson_classrooms_path(@lesson.id), method: :post, class:"btn btn-primary btn-round"   %>
              <div class="ripple-container"></div>
              <% end %>
            <p><%= raw(@lesson.content) %></p>
          </div>
        </div>
      </div>
      <div class="section section-blog-info">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <div class="row">
              <div class="col-md-6">
                <div class="blog-tags">
                  Catégorie :
                  <span class="badge badge-primary badge-pill"><%= @lesson.category %></span>
                </div>
              </div>
            </div>
            <hr>
          </div>
        </div>
      </div>
      <div class="section section-comments">
        <div class="row">        
          <div class="col-md-8 ml-auto mr-auto">
            <div class="media-area">
              <h3 class="title text-center">Commentaires</h3>
              <% @comments.each do |comment| %> 
                <% if @lesson.id == comment.lesson_id %>
              <div class="media">  
                  <div class="avatar">
                  <%if comment.user.avatar.attached?%>
                    <%= image_tag comment.user.avatar, alt: 'avatar', class:"avatar img-raised" %>
                  <%else%>
                    <%= image_tag "avatar/void_avatar.jpg", alt: 'avatar', class:"avatar img-raised" %>
                  <%end%>    
                  </div>
                <% if @lesson.id == comment.lesson_id %>      
                <div class="media-body">
                  <h4 class="media-heading"><%= comment.user.username %><small>  Posté le <%= comment.created_at.strftime("%d/%m/%Y")%> à <%= comment.created_at.strftime("%H:%M:%S")%></small></h4>
                  <h6 class="text-muted"></h6>
                  <p><%= comment.content %></p>
                  <br>
                    <% if session[:user_id]%> 
                      <% if current_user.id == @lesson.user_id || current_user.id == comment.user_id%>
                      <%end%>
                    <%end%>
                </div>   
              </div>
                  <% end %>
                <% end %>
              <% end %>
              <h3 class="text-center">Laissez votre commentaire <br></h3>
              <div class="media media-post">
                  <div class="avatar">
                      <%if current_user.avatar.attached?%>
                        <%= image_tag current_user.avatar, alt: 'avatar', class:"avatar img-raised" %>
                      <%else%>
                      <%= image_tag "avatar/void_avatar.jpg", alt: 'avatar', class:"avatar img-raised" %>
                      <%end%>
                  </div>
                <div class="media-body">
                    <%= form_with model: @comment, url: [@lesson, @comment], local: true, class: "form" do |form| %>
                  <div class="form-group label-floating bmd-form-group">
                    <%= form.text_field :content, class: "form-control", placeholder: "Contenu du commentaire" %>           
                  </div>
                  <div class="media-footer">
                    <%= form.submit class: "btn btn-primary btn-round btn-wd float-right", value: "Poster le commentaire" %>
                  </div>
                    <% end %>
                </div>
              </div>       
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>